source 'https://rubygems.org'

gem 'edn', '~> 1.1'
gem 'git', '~> 1.9'
gem 'mime-types', '~> 3.3'
gem 'rake', '~> 13.0'
gem 'rake_github', '0.8.0.pre.5'
gem 'rake_gpg', '~> 0.16'
gem 'rake_ssh', '~> 0.4'
gem 'rake_dependencies', '~> 3.1'
gem 'semantic', '~> 1.6'
gem 'rake_fly', '~> 2.11'
gem 'confidante', '~> 0.27'
gem 'rake_terraform', '~> 1.20'
