resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: source
    type: git
    source:
      uri: ((source_repository_url))
      branch: ((source_repository_branch))
      private_key: ((git_ssh_key))

  - name: dist
    type: s3
    source:
      bucket: ((storage_bucket_name))
      regexp: otel-extension/artifacts/otel-extension-(.*)-standalone.jar
      region_name: ((storage_bucket_region))
      server_side_encryption: ((storage_bucket_encryption))
      access_key_id: ((aws_access_key_id))
      secret_access_key: ((aws_secret_access_key))
      private: true

  - name: version
    type: semver
    source:
      driver: s3
      initial_version: 0.1.0
      bucket: ((storage_bucket_name))
      key: otel-extension/metadata/version
      region_name: ((storage_bucket_region))
      server_side_encryption: ((storage_bucket_encryption))
      access_key_id: ((aws_access_key_id))
      secret_access_key: ((aws_secret_access_key))

  - name: application-builder-image
    type: docker-image
    source:
      repository: ((application_builder_image_repository))
      tag: ((application_builder_image_tag))

  - name: notify-success
    type: slack-notification
    source:
      url: ((slack_builds_webhook_url))

  - name: notify-failure
    type: slack-notification
    source:
      url: ((slack_development_webhook_url))

jobs:
  - name: build
    plan:
      - in_parallel:
        - get: source
          trigger: true
        - put: version
          params:
            pre: rc
        - get: application-builder-image
      - task: build
        file: source/pipelines/build/task.yaml
        image: application-builder-image
        params:
          GPG_KEY: ((gpg_key))
          PROVISIONING_ROLE_ARN: ((ci_provisioning_role_arn))
          DEPLOYMENT_TYPE: ((ci_deployment_type))
          DEPLOYMENT_LABEL: ((ci_deployment_label))

      - put: dist
        params:
          file: dist/otel-extension-*-standalone.jar

    on_success:
      put: notify-success
      params:
        text: ((slack_success_message))
        channel: ((slack_success_channel))

    on_failure:
      put: notify-failure
      params:
        text: ((slack_failure_message))
        channel: ((slack_failure_channel))

    on_error:
      put: notify-failure
      params:
        text: ((slack_error_message))
        channel: ((slack_error_channel))

    on_abort:
      put: notify-failure
      params:
        text: ((slack_abort_message))
        channel: ((slack_abort_channel))
