---
vars:
  pipeline_builder_image_repository: "%{hiera('pipeline_builder_image_repository')}"
  service_image_repository: "%{hiera('service_image_repository')}"
  application_builder_image_repository: "%{hiera('application_builder_image_repository')}"
  application_builder_image_tag: "%{hiera('application_builder_image_tag')}"

  storage_bucket_name: "%{hiera('storage_bucket_name')}"
  storage_bucket_region: "%{hiera('ci_region')}"
  storage_bucket_encryption: "%{hiera('storage_bucket_encryption')}"

  ci_provisioning_role_arn: "%{hiera('ci_provisioning_role_arn')}"
  ci_deployment_type: "%{hiera('ci_deployment_type')}"
  ci_deployment_label: "%{hiera('ci_deployment_label')}"

  source_repository_url: "%{hiera('source_repository_url')}"
  source_repository_branch: "%{hiera('source_repository_branch')}"

  slack_success_channel: "#builds"
  slack_success_message: "<%{hiera('ci_server_url')}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME:$BUILD_JOB_NAME [$BUILD_NAME]> _successful_! :clap:."
  slack_error_channel: "#development"
  slack_error_message: "<%{hiera('ci_server_url')}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME:$BUILD_JOB_NAME [$BUILD_NAME]> *errored*! :cry:."
  slack_failure_channel: "#development"
  slack_failure_message: "<%{hiera('ci_server_url')}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME:$BUILD_JOB_NAME [$BUILD_NAME]> *failed*! :cry:."
  slack_abort_channel: "#development"
  slack_abort_message: "<%{hiera('ci_server_url')}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME:$BUILD_JOB_NAME [$BUILD_NAME]> *aborted*! :warning:."
